# Base Image
FROM stereolabs/zed:4.0-gl-devel-cuda11.4-ubuntu20.04
LABEL authors="Missouri S&T Mars Rover Design Team"
LABEL maintainer="Mars Rover Design Team <marsrover@mst.edu>"
LABEL org.opencontainers.image.source=https://github.com/missourimrdt/rovecomm_cpp
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.description="v24.0.0"
ARG DEBIAN_FRONTEND=noninteractive

# Install Necessary Packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential gcc g++ gdb cmake git libgtk2.0-dev pkg-config \
    libavcodec-dev libavformat-dev libswscale-dev \
    libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev \
    yasm libatlas-base-dev gfortran libpq-dev libxine2-dev \
    libglew-dev libtiff5-dev zlib1g-dev libavutil-dev libpostproc-dev \
    libeigen3-dev python3-dev python3-pip python3-numpy libx11-dev tzdata \
    libboost-all-dev valgrind doxygen graphviz && \
    rm -rf /var/lib/apt/lists/*

# Install CMake
ARG INSTALL_CMAKE_VERSION_FROM_SOURCE="3.24.3"
COPY install-cmake.sh /tmp/

RUN if [ "${INSTALL_CMAKE_VERSION_FROM_SOURCE}" != "none" ]; then \
    chmod +x /tmp/install-cmake.sh && /tmp/install-cmake.sh ${INSTALL_CMAKE_VERSION_FROM_SOURCE}; \
    fi && \
    rm -f /tmp/install-cmake.sh

# Set Working Directory
WORKDIR /opt

# Install Quill from Source
ARG QUILL_VERSION="v3.2.0"
RUN git clone --depth 1 --branch ${QUILL_VERSION} http://github.com/odygrd/quill.git && \
    mkdir quill/build && \
    cd quill/build && \
    cmake .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf quill

# Install Google Test from Source
ARG GOOGLE_TEST_VERSION="v1.13.0"
RUN git clone --depth 1 --branch ${GOOGLE_TEST_VERSION} https://github.com/google/googletest.git && \
    mkdir googletest/build && \
    cd googletest/build && \
    cmake .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf googletest

# Set Linux Environment Variable for Make Threads. Runs everytime a terminal is opened.
RUN echo 'export MAKEFLAGS=-j$(($(grep -c "^processor" /proc/cpuinfo) - 1))' >> .bashrc

# Clone your C++ project repository
RUN git clone --recurse-submodules -j8 https://github.com/MissouriMRDT/RoveComm_CPP.git

# Set the working directory TO BUILD
WORKDIR /RoveComm_CPP/