# Image Variables
ARG UBUNTU_MAJOR="20"
ARG CUDA_MAJOR="11"
ARG CUDA_MINOR="7"
ARG CUDA_PATCH="0"

# Base Image
FROM nvcr.io/nvidia/cuda:${CUDA_MAJOR}.${CUDA_MINOR}.${CUDA_PATCH}-devel-ubuntu${UBUNTU_MAJOR}.04

# Install Variables
ARG UBUNTU_MAJOR="20"
ARG CUDA_MAJOR="11"
ARG CUDA_MINOR="7"
ARG CUDA_PATCH="0"
ARG CMAKE_VERSION="3.24.3"
ARG QUILL_VERSION="v3.3.1"
ARG GTEST_VERSION="v1.14.0"

# Set Labels
LABEL authors="Missouri S&T Mars Rover Design Team"
LABEL maintainer="Mars Rover Design Team <marsrover@mst.edu>"
LABEL org.opencontainers.image.source=https://github.com/missourimrdt/rovecomm_cpp
LABEL org.opencontainers.image.licenses=GPL-3.0-onlyLABEL
LABEL org.opencontainers.image.version="v24.0.0"
LABEL org.opencontainers.image.description="Docker Image for Ubuntu ${UBUNTU_MAJOR}.${UBUNTU_MINOR} with CUDA ${CUDA_MAJOR}.${CUDA_MINOR}, Quill ${QUILL_VERSION}, and Google Test ${GTEST_VERSION}."

# Set Non-Interactive Mode
ARG DEBIAN_FRONTEND=noninteractive

# Set NVIDIA Driver Enviroment Variables
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}compute,video,utility,graphics

# Set Timezone
RUN echo "America/Chicago" > /etc/localtime

# Set CUDA Version
RUN echo "CUDA Version ${CUDA_MAJOR}.${CUDA_MINOR}.0" > /usr/local/cuda/version.txt

# Install Required Ubuntu Packages
RUN rm /etc/apt/sources.list.d/cuda.list && apt-get update && \
    apt-get install --no-install-recommends -y \
    build-essential gdb wget less udev zstd sudo libgomp1 libswscale-dev \
    cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev \
    libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev tzdata curl \
    yasm libatlas-base-dev gfortran libpq-dev libavutil-dev libpostproc-dev \
    libxine2-dev libglew-dev libtiff5-dev zlib1g-dev cowsay locales \
    libeigen3-dev python3-dev python3-pip python3-numpy libx11-dev \
    libboost-all-dev valgrind doxygen graphviz htop nano fortune fortunes

# Install Required Python Packages
RUN python3 -m pip install numpy opencv-python pyopengl

# Install gcc/g++
RUN apt-get install  --no-install-recommends -y \
    gcc-10 g++-10 && \
    rm -rf /var/lib/apt/lists/* && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ \
    g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10

# Install CMake
COPY install-cmake.sh /tmp/
RUN if [ "${CMAKE_VERSION}" != "none" ]; then \
        chmod +x /tmp/install-cmake.sh && /tmp/install-cmake.sh ${CMAKE_VERSION}; \
    fi && \
    rm -f /tmp/install-cmake.sh

# Set Working Directory
WORKDIR /opt

# Install Quill from Source
RUN git clone --depth 1 --branch ${QUILL_VERSION} http://github.com/odygrd/quill.git && \
    mkdir quill/build && \
    cd quill/build && \
    cmake .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf quill

# Install Google Test from Source
RUN git clone --depth 1 --branch ${GTEST_VERSION} https://github.com/google/googletest.git && \
    mkdir googletest/build && \
    cd googletest/build && \
    cmake .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf googletest

# Enable Make Threads
RUN echo 'export MAKEFLAGS=-j$(($(grep -c "^processor" /proc/cpuinfo) - 1))' >> /root/.bashrc

# Fix Perl Locale Error
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

# Clone RoveComm CPP Repository
RUN git clone --recurse-submodules -j8 https://github.com/MissouriMRDT/RoveComm_CPP.git

# Set Working Directory
WORKDIR /opt/RoveComm_CPP/
