# Base Image
FROM stereolabs/zed:4.0-tools-devel-jetson-jp5.1.1
LABEL authors="Missouri S&T Mars Rover Design Team"
LABEL maintainer="Mars Rover Design Team <marsrover@mst.edu>"
LABEL org.opencontainers.image.source=https://github.com/missourimrdt/rovecomm_cpp
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.description="v24.0.0"
ARG DEBIAN_FRONTEND=noninteractive

# Install Necessary Packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential gfortran cmake git gdb file tar libatlas-base-dev \
    libavcodec-dev libavformat-dev libavresample-dev libcanberra-gtk3-module \
    libdc1394-22-dev libeigen3-dev libglew-dev libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-good1.0-dev libgstreamer1.0-dev libgtk-3-dev libjpeg-dev \
    libjpeg8-dev libjpeg-turbo8-dev liblapack-dev liblapacke-dev libopenblas-dev libpng-dev \
    libpostproc-dev libswscale-dev libtbb-dev libtbb2 libtesseract-dev libtiff-dev libv4l-dev \
    libxine2-dev libxvidcore-dev libx264-dev libgtkglext1 libgtkglext1-dev pkg-config qv4l2 \
    v4l-utils zlib1g-dev python3-dev python-numpy libboost-all-dev valgrind doxygen graphviz && \
    rm -rf /var/lib/apt/lists/*

# Install CMake
ARG INSTALL_CMAKE_VERSION_FROM_SOURCE="3.24.3"
COPY install-cmake.sh /tmp/

RUN if [ "${INSTALL_CMAKE_VERSION_FROM_SOURCE}" != "none" ]; then \
    chmod +x /tmp/install-cmake.sh && /tmp/install-cmake.sh ${INSTALL_CMAKE_VERSION_FROM_SOURCE}; \
    fi && \
    rm -f /tmp/install-cmake.sh

# Set Working Directory
WORKDIR /opt

# Install Quill from Source
ARG QUILL_VERSION="v3.2.0"
RUN git clone --depth 1 --branch ${QUILL_VERSION} http://github.com/odygrd/quill.git && \
    mkdir quill/build && \
    cd quill/build && \
    cmake .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf quill

# Install Google Test from Source
ARG GOOGLE_TEST_VERSION="v1.13.0"
RUN git clone --depth 1 --branch ${GOOGLE_TEST_VERSION} https://github.com/google/googletest.git && \
    mkdir googletest/build && \
    cd googletest/build && \
    cmake .. && \
    make && \
    make install && \
    cd ../.. && \
    rm -rf googletest

# Set Linux Environment Variable for Make Threads. Runs everytime a terminal is opened.
RUN echo 'export MAKEFLAGS=-j$(($(grep -c "^processor" /proc/cpuinfo) - 1))' >> .bashrc

# Clone your C++ project repository
RUN git clone --recurse-submodules -j8 https://github.com/MissouriMRDT/RoveComm_CPP.git

# Set the working directory TO BUILD
WORKDIR /RoveComm_CPP/
