name: Update Manifest Header

on:
  pull_request:
    branches: ["development"]
    # Triggers on any push to the PR if these specific paths change.
    paths:
      - "data/RoveComm"
      - "tools/RoveComm/parser.py"
      - ".github/workflows/manifest.yml"
  workflow_dispatch:

# Grant permission to push changes back to the repo.
permissions:
  contents: write

concurrency:
  group: "manifest-generator"
  cancel-in-progress: true

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # Checkout the actual PR branch (HEAD) instead of the merge commit.
          ref: ${{ github.head_ref }}

      - name: Setup Git
        run: |
          git config user.name "MissouriMRDT"
          git config user.email "marsrover@mst.edu"

      - name: Generate Manifest
        run: |
          cd tools/RoveComm
          python parser.py

      - name: Commit Manifest
        run: |
          git add -f src/RoveComm/RoveCommManifest.h
          git commit -m "** Automated - Manifest Update **" || echo "No changes to commit"

      - name: Push Changes
        run: |
          # Push strictly to the branch attached to this Pull Request
          git push origin HEAD:${{ github.head_ref }} --force-with-lease || echo "Failed to push changes"
