name: Unit and Integration Tests

on:
  pull_request:
    branches: ["development"]
  push:
    branches: ["development"]
  workflow_dispatch:

concurrency:
  group: "unit-tests"
  cancel-in-progress: false

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: ghcr.io/missourimrdt/rovecomm-jammy:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Tests
        run: |
          mkdir build
          cd build
          cmake -DBUILD_TESTS_MODE=ON ..
          make

      - name: Run Unit Tests
        id: run-unit
        run: |
          cd build
          if test -f "RoveComm_CPP_UnitTests"; then ./RoveComm_CPP_UnitTests ; else echo "No Unit Tests Exist" ; fi

      - name: Run Integration Tests
        id: run-integration
        if: success() || (failure() && steps.run-unit.outcome == 'failure')
        run: |
          cd build
          if test -f "RoveComm_CPP_IntegrationTests"; then ./RoveComm_CPP_IntegrationTests ; else echo "No Integration Tests Exist" ; fi
