name: Valgrind Memory Check

on:
  pull_request:
    branches: ["development"]
  push:
    branches: ["development"]
  workflow_dispatch:

concurrency:
  group: "valgrind"
  cancel-in-progress: false

jobs:
  run-valgrind:
    runs-on: ubuntu-latest
    container: ghcr.io/missourimrdt/rovecomm-jammy:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Executable
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run Valgrind
        run: |
          chmod +x tools/valgrind/run_valgrind.sh
          ./tools/valgrind/run_valgrind.sh "CI-Workspace"

      - name: Analyze Valgrind - Definitely Lost
        if: success() || failure()
        run: |
          cd tools/valgrind
          if ! grep 'definitely lost' valgrind.rpt; then exit 0; fi
          if grep 'definitely lost: 0' valgrind.rpt; then exit 0; else exit 1; fi

      - name: Analyze Valgrind - Indirectly Lost
        if: success() || failure()
        run: |
          cd tools/valgrind
          if ! grep 'indirectly lost' valgrind.rpt; then exit 0; fi
          if grep 'indirectly lost: 0' valgrind.rpt; then exit 0; else exit 1; fi

      - name: Analyze Valgrind - Possibly Lost
        if: success() || failure()
        run: |
          cd tools/valgrind
          if ! grep 'possibly lost' valgrind.rpt; then exit 0; fi
          if grep 'possibly lost: 0' valgrind.rpt; then exit 0; else exit 0; fi

      - name: Analyze Valgrind - Still Reachable
        if: success() || failure()
        run: |
          cd tools/valgrind
          if ! grep 'still reachable' valgrind.rpt; then exit 0; fi
          if grep 'still reachable: 0' valgrind.rpt; then exit 0; else exit 0; fi

      - name: Upload Valgrind Log
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: valgrind.rpt
          path: tools/valgrind/valgrind.rpt
          retention-days: 1
